2024-04-23 20:36:17,580 : INFO : root : Loading config.
2024-04-23 20:36:17,582 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2024-04-23 20:36:17,582 : WARNING : ConfigProcessor : Config file in cache changed: /home/mpfuser/pinball/Futurama31/config/config.yaml
2024-04-23 20:36:17,583 : INFO : ConfigProcessor : Loading config from file /usr/local/lib/python3.7/dist-packages/mpf/mpfconfig.yaml.
2024-04-23 20:36:17,631 : INFO : ConfigProcessor : Loading config: /usr/local/lib/python3.7/dist-packages/mpf/mpfconfig.yaml
2024-04-23 20:36:17,631 : INFO : ConfigProcessor : Loading config from file /home/mpfuser/pinball/Futurama31/config/config.yaml.
2024-04-23 20:36:17,767 : INFO : ConfigProcessor : Loading config: /home/mpfuser/pinball/Futurama31/config/config.yaml
2024-04-23 20:36:17,769 : INFO : ConfigProcessor : Config file cache created: /tmp/9f2098f750e45235613be58ba15b9646.mpf_cache
2024-04-23 20:36:17,795 : INFO : ConfigProcessor : Loading config from cache: /tmp/0488c24d6cb11f71168a087186f8afaf.mpf_cache
2024-04-23 20:36:17,795 : INFO : ConfigProcessor : Loading config from cache: /tmp/7559345efe69122f4d6fb5f65214b482.mpf_cache
2024-04-23 20:36:17,795 : INFO : ConfigProcessor : Loading config from cache: /tmp/ea6b25128768fa7bfd9e42011d34475f.mpf_cache
2024-04-23 20:36:17,795 : INFO : ConfigProcessor : Loading config from cache: /tmp/fecad1d527faf1d03547df1920e5db10.mpf_cache
2024-04-23 20:36:17,796 : INFO : ConfigProcessor : Loading config from cache: /tmp/fcc4c9d209c9a032c06d4f66ec129faa.mpf_cache
2024-04-23 20:36:17,796 : INFO : ConfigProcessor : Loading config from cache: /tmp/1589a8837fa04fabe2b0cb060c0683ab.mpf_cache
2024-04-23 20:36:17,796 : INFO : Machine : Mission Pinball Framework Core Engine v0.55.0
2024-04-23 20:36:17,796 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs/2024-04-23-20-36-17-mpf-futurama.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2024-04-23 20:36:17,796 : INFO : Machine : MPF path: /usr/local/lib/python3.7/dist-packages/mpf
2024-04-23 20:36:17,796 : INFO : Machine : Machine path: /home/mpfuser/pinball/Futurama31
2024-04-23 20:36:17,796 : INFO : Machine : Platform: linux
2024-04-23 20:36:17,796 : INFO : Machine : Python executable location: /usr/bin/python3
2024-04-23 20:36:17,796 : INFO : Machine : Python version: 3.7.3 (64-bit)
2024-04-23 20:36:17,797 : INFO : Machine : Initialise MPF.
2024-04-23 20:36:17,824 : INFO : P-Roc : Connecting to P-ROC
2024-04-23 20:36:17,880 : INFO : P-Roc : Successfully connected to P-ROC/P3-ROC. Firmware Version: 2. Firmware Revision: 14. Hardware Board ID: 1
2024-04-23 20:36:17,893 : INFO : EventManager : Event: ======'machine_var_p_roc_version'====== Args={'value': 2, 'prev_value': None, 'change': True}
2024-04-23 20:36:17,893 : INFO : EventManager : Event: ======'machine_var_p_roc_revision'====== Args={'value': 14, 'prev_value': None, 'change': True}
2024-04-23 20:36:17,893 : INFO : EventManager : Event: ======'machine_var_p_roc_hardware_version'====== Args={'value': 1, 'prev_value': None, 'change': True}
2024-04-23 20:36:17,893 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2024-04-23 20:36:17,919 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.9, 'prev_value': None, 'change': True}
2024-04-23 20:36:17,919 : INFO : EventManager : Event: ======'machine_var_player1_score'====== Args={'value': 3376, 'prev_value': None, 'change': True}
2024-04-23 20:36:17,919 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'MPF v0.55.0', 'prev_value': None, 'change': True}
2024-04-23 20:36:17,919 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'MPF v0.55.0, Config version:5, Show version: 5, BCP version:1.1', 'prev_value': None, 'change': True}
2024-04-23 20:36:17,919 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.7.3', 'prev_value': None, 'change': True}
2024-04-23 20:36:17,920 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Linux-4.19.0-20-amd64-x86_64-with-debian-10.12', 'prev_value': None, 'change': True}
2024-04-23 20:36:17,920 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Linux', 'prev_value': None, 'change': True}
2024-04-23 20:36:17,920 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '4.19.0-20-amd64', 'prev_value': None, 'change': True}
2024-04-23 20:36:17,920 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '#1 SMP Debian 4.19.235-1 (2022-03-17)', 'prev_value': None, 'change': True}
2024-04-23 20:36:17,920 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'x86_64', 'prev_value': None, 'change': True}
2024-04-23 20:36:17,920 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2024-04-23 20:36:17,940 : INFO : EventManager : Event: ======'drop_target_bank_crew_bank_up'====== Args={}
2024-04-23 20:36:17,968 : INFO : EventManager : Event: ======'init_phase_2'====== Args={}
2024-04-23 20:36:17,984 : INFO : SwitchController : Found active switch: (30, <Platform.P3-ROC>) <switch.s_trough1>
2024-04-23 20:36:17,984 : INFO : SwitchController : Found active switch: (28, <Platform.P3-ROC>) <switch.s_pe_platter>
2024-04-23 20:36:17,984 : INFO : SwitchController : Found active switch: (23, <Platform.P3-ROC>) <switch.s_dt_nibbler>
2024-04-23 20:36:17,993 : INFO : EventManager : Event: ======'bcp_connection_attempt'====== Args={'name': 'local_display', 'host': 'localhost', 'port': 5050}
2024-04-23 20:36:17,996 : INFO : BCPClientSocket : Connecting BCP to 'local_display' at localhost:5050...
2024-04-23 20:36:19,032 : INFO : BCPClientSocket : Connected BCP to 'local_display' localhost:5050
2024-04-23 20:36:19,033 : INFO : EventManager : Event: ======'bcp_clients_connected'====== Args={}
2024-04-23 20:36:19,034 : INFO : ball_device.bd_trough : BCH: Initial count: 1
2024-04-23 20:36:19,034 : INFO : ball_device.bd_trough : State: idle
2024-04-23 20:36:19,034 : INFO : ball_device.bd_plunger : BCH: Initial count: 0
2024-04-23 20:36:19,035 : INFO : ball_device.bd_plunger : State: idle
2024-04-23 20:36:19,035 : INFO : ball_device.bd_VUK : BCH: Initial count: 0
2024-04-23 20:36:19,035 : INFO : ball_device.bd_VUK : State: idle
2024-04-23 20:36:19,035 : ERROR : asyncio : Task exception was never retrieved
future: <Task finished coro=<BallDevice._initialize_async() done, defined at /usr/local/lib/python3.7/dist-packages/mpf/devices/ball_device/ball_device.py:195> exception=ConfigFileError("Ball device 'bd_left_post' uses switch 's_left_loop' which has a 'playfield_active' tag. This is handled internally by the device. Remove the redundant 'playfield_active' tag from that switch.")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mpf/devices/ball_device/ball_device.py", line 197, in _initialize_async
    await self.ball_count_handler.initialise()
  File "/usr/local/lib/python3.7/dist-packages/mpf/devices/ball_device/ball_count_handler.py", line 92, in initialise
    self.counter = counter_class(self.ball_device, self.ball_device.config.get("counter", {}))
  File "/usr/local/lib/python3.7/dist-packages/mpf/devices/ball_device/switch_counter.py", line 86, in __init__
    self.ball_device.config['captures_from'].name), 13)
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/logging.py", line 173, in raise_config_error
    from source_exception
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ball_device.bd_left_post: Ball device 'bd_left_post' uses switch 's_left_loop' which has a 'playfield_active' tag. This is handled internally by the device. Remove the redundant 'playfield_active' tag from that switch. Error Code: CFE-ball_device-13 (https://docs.missionpinball.org/en/0.55/logs/CFE-ball_device-13.html)
2024-04-23 20:36:19,047 : ERROR : asyncio : Task exception was never retrieved
future: <Task finished coro=<BallDevice._initialize_async() done, defined at /usr/local/lib/python3.7/dist-packages/mpf/devices/ball_device/ball_device.py:195> exception=ConfigFileError("Ball device 'bd_right_post' uses switch 's_right_loop' which has a 'playfield_active' tag. This is handled internally by the device. Remove the redundant 'playfield_active' tag from that switch.")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mpf/devices/ball_device/ball_device.py", line 197, in _initialize_async
    await self.ball_count_handler.initialise()
  File "/usr/local/lib/python3.7/dist-packages/mpf/devices/ball_device/ball_count_handler.py", line 92, in initialise
    self.counter = counter_class(self.ball_device, self.ball_device.config.get("counter", {}))
  File "/usr/local/lib/python3.7/dist-packages/mpf/devices/ball_device/switch_counter.py", line 86, in __init__
    self.ball_device.config['captures_from'].name), 13)
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/logging.py", line 173, in raise_config_error
    from source_exception
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ball_device.bd_right_post: Ball device 'bd_right_post' uses switch 's_right_loop' which has a 'playfield_active' tag. This is handled internally by the device. Remove the redundant 'playfield_active' tag from that switch. Error Code: CFE-ball_device-13 (https://docs.missionpinball.org/en/0.55/logs/CFE-ball_device-13.html)
2024-04-23 20:36:19,050 : INFO : Machine : Starting the main run loop.
2024-04-23 20:36:19,082 : INFO : EventManager : Event: ======'init_phase_3'====== Args={}
2024-04-23 20:36:19,082 : INFO : Machine : Shutting down...
2024-04-23 20:36:19,082 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2024-04-23 20:36:19,087 : ERROR : asyncio : Exception in callback EventManager._queue_task_done(<Task finishe...y not found')>)
handle: <Handle EventManager._queue_task_done(<Task finishe...y not found')>)>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/events.py", line 728, in _queue_task_done
    future.result()
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/events.py", line 645, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/config_player.py", line 84, in _initialise_system_wide
    self.machine.config[self.config_file_section])
  File "/usr/local/lib/python3.7/dist-packages/mpf/config_players/plugin_player.py", line 55, in register_player_events
    self.bcp_client = self._get_bcp_client(config)
  File "/usr/local/lib/python3.7/dist-packages/mpf/config_players/plugin_player.py", line 34, in _get_bcp_client
    "bcp connection {} not found".format(client_name))
AssertionError: bcp connection local_display not found
2024-04-23 20:36:19,116 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/machine.py", line 769, in _run_loop
    raise self._exception['exception']
  File "/usr/local/lib/python3.7/dist-packages/mpf/devices/ball_device/ball_device.py", line 197, in _initialize_async
    await self.ball_count_handler.initialise()
  File "/usr/local/lib/python3.7/dist-packages/mpf/devices/ball_device/ball_count_handler.py", line 92, in initialise
    self.counter = counter_class(self.ball_device, self.ball_device.config.get("counter", {}))
  File "/usr/local/lib/python3.7/dist-packages/mpf/devices/ball_device/switch_counter.py", line 86, in __init__
    self.ball_device.config['captures_from'].name), 13)
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/logging.py", line 173, in raise_config_error
    from source_exception
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ball_device.bd_left_post: Ball device 'bd_left_post' uses switch 's_left_loop' which has a 'playfield_active' tag. This is handled internally by the device. Remove the redundant 'playfield_active' tag from that switch. Error Code: CFE-ball_device-13 (https://docs.missionpinball.org/en/0.55/logs/CFE-ball_device-13.html)
